// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCghacdAnXggFmaQ4_mWIEI1ZsUbzhbaF0',
    appId: '1:525912087392:web:078792208fafea4dae5c05',
    messagingSenderId: '525912087392',
    projectId: 'audioplayer-517db',
    authDomain: 'audioplayer-517db.firebaseapp.com',
    storageBucket: 'audioplayer-517db.appspot.com',
    measurementId: 'G-VH8DF4QLPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxIGYfhR4walS-51nKomaUvtsRidHIDpM',
    appId: '1:525912087392:android:c0924509cb01c6acae5c05',
    messagingSenderId: '525912087392',
    projectId: 'audioplayer-517db',
    storageBucket: 'audioplayer-517db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByQf2EfzcNeKY1U7WrbZlBpBbAP4dgEqg',
    appId: '1:525912087392:ios:bad7aa18c6ee525fae5c05',
    messagingSenderId: '525912087392',
    projectId: 'audioplayer-517db',
    storageBucket: 'audioplayer-517db.appspot.com',
    iosBundleId: 'com.example.musicPlayerR',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByQf2EfzcNeKY1U7WrbZlBpBbAP4dgEqg',
    appId: '1:525912087392:ios:0f62ee902ec2b8a1ae5c05',
    messagingSenderId: '525912087392',
    projectId: 'audioplayer-517db',
    storageBucket: 'audioplayer-517db.appspot.com',
    iosBundleId: 'com.example.audioPlayer.RunnerTests',
  );
}
